# Generated by Django 3.2.5 on 2022-03-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contract',
            new_name='contract_1',
        ),
    ]
